language: ruby

cache: bundler
sudo: false

branches:
  - master
  - /^v\d+\.\d+(?:\.\d+)?(?:-\S*)?$/

bundler_args: "--without development --with ci"

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-9.2.7.0

matrix:
  include:
    - rvm: 2.6
      after_script: "bundle exec codeclimate-test-reporter"

  allow_failures:
    - rvm: ruby-head
