language: ruby

cache: bundler
sudo: false

branches:
  - master
  - /^v\d+\.\d+(?:\.\d+)?(?:-\S*)?$/

bundler_args: "--jobs 4 --retry 3 --without development"

rvm:
  - 2.4
  - 2.5
  - ruby-head
  - jruby-9.2.7.0

matrix:
  include:
    - rvm: 2.6
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

  allow_failures:
    - rvm: ruby-head
